# Generated by Django 4.2.2 on 2023-06-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user_remove_message_room_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
